use Kabra
go

/* Insert Controllers */
insert into dbo.Controllers values('ModbusRtuController_1', 'RMU 1', 'ModbusRtu', '1', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_2', 'RMU 2', 'ModbusRtu', '2', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_3', 'RMU 3', 'ModbusRtu', '3', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_4', 'RMU 4', 'ModbusRtu', '4', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_5', 'RMU 5', 'ModbusRtu', '5', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_6', 'RMU 6', 'ModbusRtu', '6', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_7', 'RMU 7', 'ModbusRtu', '7', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_8', 'RMU 8', 'ModbusRtu', '8', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_9', 'RMU 9', 'ModbusRtu', '9', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_10', 'RMU 10', 'ModbusRtu', '10', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_11', 'RMU 11', 'ModbusRtu', '11', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_12', 'RMU 12', 'ModbusRtu', '12', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_13', 'RMU 13', 'ModbusRtu', '13', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_14', 'RMU 14', 'ModbusRtu', '14', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_15', 'RMU 15', 'ModbusRtu', '15', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_16', 'RMU 16', 'ModbusRtu', '16', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_17', 'RMU 17', 'ModbusRtu', '17', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_18', 'RMU 18', 'ModbusRtu', '18', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_19', 'RMU 19', 'ModbusRtu', '19', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_20', 'RMU 20', 'ModbusRtu', '20', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_21', 'RMU 21', 'ModbusRtu', '21', 'COM3', 100)

insert into dbo.Controllers values('ModbusRtuController_22', 'RMS 22', 'ModbusRtu', '22', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_23', 'RMS 23', 'ModbusRtu', '23', 'COM3', 100)
insert into dbo.Controllers values('ModbusRtuController_24', 'RMS 24', 'ModbusRtu', '24', 'COM3', 100)

/* Insert Used Memory Addresses */
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_1', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_2', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_3', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_4', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_5', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_6', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_7', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_8', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_9', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_10', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_11', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_12', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_13', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_14', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_15', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_16', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_17', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_18', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_19', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_20', '30000|12')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_21', '30000|12')

insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_22', '40000|8')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_23', '40000|8')
insert into dbo.UsedMemoryAddressesInControllers values('ModbusRtuController_24', '40000|8')
