use Kabra
go

insert into dbo.FieldPoints values('Current_R', 'Current_R', 'FieldPoint', '30006|2', 'float', 'true', 'false', 'currentSensors_1',null, null, null, 'ModbusRtuController_1', 'Motor_1')
insert into dbo.FieldPoints values('Current_Y', 'Current_Y', 'FieldPoint', '30008|2', 'float', 'true', 'false', 'currentSensors_1',null, null, null, 'ModbusRtuController_1', 'Motor_1')
insert into dbo.FieldPoints values('Current_B', 'Current_B', 'FieldPoint', '30010|2', 'float', 'true', 'false', 'currentSensors_1',null, null, null, 'ModbusRtuController_1', 'Motor_1')
insert into dbo.FieldPoints values('Voltage_1', 'Voltage_1', 'FieldPoint', '30000|2', 'float', 'true', 'false', 'voltageSensors_1',null, null, null, 'ModbusRtuController_1', 'Motor_1')
insert into dbo.FieldPoints values('Voltage_2', 'Voltage_2', 'FieldPoint', '30002|2', 'float', 'true', 'false', 'voltageSensors_1',null, null, null, 'ModbusRtuController_1', 'Motor_1')
insert into dbo.FieldPoints values('Voltage_3', 'Voltage_3', 'FieldPoint', '30004|2', 'float', 'true', 'false', 'voltageSensors_1',null, null, null, 'ModbusRtuController_1', 'Motor_1')
insert into dbo.FieldPoints values('Vibration', 'Vibration', 'FieldPoint', '40000|1', 'float', 'true', 'false', 'vibrationSensors_1', '25', null, null, 'ModbusRtuController_22', 'Motor_1')
insert into dbo.FieldPoints values('Status', 'Status', 'FieldPoint', '30006|2', 'bool', 'false', 'false', 'statusSensors_1',null, null, null, 'ModbusRtuController_1', 'Motor_1')

insert into dbo.FieldPoints values('Current_R', 'Current_R', 'FieldPoint', '30006|2', 'float', 'true', 'false', 'currentSensors_2',null, null, null, 'ModbusRtuController_2', 'Motor_2')
insert into dbo.FieldPoints values('Current_Y', 'Current_Y', 'FieldPoint', '30008|2', 'float', 'true', 'false', 'currentSensors_2',null, null, null, 'ModbusRtuController_2', 'Motor_2')
insert into dbo.FieldPoints values('Current_B', 'Current_B', 'FieldPoint', '30010|2', 'float', 'true', 'false', 'currentSensors_2',null, null, null, 'ModbusRtuController_2', 'Motor_2')
insert into dbo.FieldPoints values('Voltage_1', 'Voltage_1', 'FieldPoint', '30000|2', 'float', 'true', 'false', 'voltageSensors_2',null, null, null, 'ModbusRtuController_2', 'Motor_2')
insert into dbo.FieldPoints values('Voltage_2', 'Voltage_2', 'FieldPoint', '30002|2', 'float', 'true', 'false', 'voltageSensors_2',null, null, null, 'ModbusRtuController_2', 'Motor_2')
insert into dbo.FieldPoints values('Voltage_3', 'Voltage_3', 'FieldPoint', '30004|2', 'float', 'true', 'false', 'voltageSensors_2',null, null, null, 'ModbusRtuController_2', 'Motor_2')
insert into dbo.FieldPoints values('Vibration', 'Vibration', 'FieldPoint', '40000|1', 'float', 'true', 'false', 'vibrationSensors_2', '25', null, null, 'ModbusRtuController_22', 'Motor_2')
insert into dbo.FieldPoints values('Status', 'Status', 'FieldPoint', '30006|2', 'bool', 'false', 'false', 'statusSensors_2',null, null, null, 'ModbusRtuController_2', 'Motor_2')

insert into dbo.FieldPoints values('Current_R', 'Current_R', 'FieldPoint', '30006|2', 'float', 'true', 'false', 'currentSensors_3',null, null, null, 'ModbusRtuController_3', 'Motor_3')
insert into dbo.FieldPoints values('Current_Y', 'Current_Y', 'FieldPoint', '30008|2', 'float', 'true', 'false', 'currentSensors_3',null, null, null, 'ModbusRtuController_3', 'Motor_3')
insert into dbo.FieldPoints values('Current_B', 'Current_B', 'FieldPoint', '30010|2', 'float', 'true', 'false', 'currentSensors_3',null, null, null, 'ModbusRtuController_3', 'Motor_3')
insert into dbo.FieldPoints values('Voltage_1', 'Voltage_1', 'FieldPoint', '30000|2', 'float', 'true', 'false', 'voltageSensors_3',null, null, null, 'ModbusRtuController_3', 'Motor_3')
insert into dbo.FieldPoints values('Voltage_2', 'Voltage_2', 'FieldPoint', '30002|2', 'float', 'true', 'false', 'voltageSensors_3',null, null, null, 'ModbusRtuController_3', 'Motor_3')
insert into dbo.FieldPoints values('Voltage_3', 'Voltage_3', 'FieldPoint', '30004|2', 'float', 'true', 'false', 'voltageSensors_3',null, null, null, 'ModbusRtuController_3', 'Motor_3')
insert into dbo.FieldPoints values('Vibration', 'Vibration', 'FieldPoint', '40000|1', 'float', 'true', 'false', 'vibrationSensors_3', '25', null, null, 'ModbusRtuController_22', 'Motor_3')
insert into dbo.FieldPoints values('Status', 'Status', 'FieldPoint', '30006|2', 'bool', 'false', 'false', 'statusSensors_3',null, null, null, 'ModbusRtuController_3', 'Motor_3')

insert into dbo.FieldPoints values('Current_R', 'Current_R', 'FieldPoint', '30006|2', 'float', 'true', 'false', 'currentSensors_4',null, null, null, 'ModbusRtuController_4', 'Motor_4')
insert into dbo.FieldPoints values('Current_Y', 'Current_Y', 'FieldPoint', '30008|2', 'float', 'true', 'false', 'currentSensors_4',null, null, null, 'ModbusRtuController_4', 'Motor_4')
insert into dbo.FieldPoints values('Current_B', 'Current_B', 'FieldPoint', '30010|2', 'float', 'true', 'false', 'currentSensors_4',null, null, null, 'ModbusRtuController_4', 'Motor_4')
insert into dbo.FieldPoints values('Voltage_1', 'Voltage_1', 'FieldPoint', '30000|2', 'float', 'true', 'false', 'voltageSensors_4',null, null, null, 'ModbusRtuController_4', 'Motor_4')
insert into dbo.FieldPoints values('Voltage_2', 'Voltage_2', 'FieldPoint', '30002|2', 'float', 'true', 'false', 'voltageSensors_4',null, null, null, 'ModbusRtuController_4', 'Motor_4')
insert into dbo.FieldPoints values('Voltage_3', 'Voltage_3', 'FieldPoint', '30004|2', 'float', 'true', 'false', 'voltageSensors_4',null, null, null, 'ModbusRtuController_4', 'Motor_4')
insert into dbo.FieldPoints values('Vibration', 'Vibration', 'FieldPoint', '40000|1', 'float', 'true', 'false', 'vibrationSensors_4', '25', null, null, 'ModbusRtuController_23', 'Motor_4')
insert into dbo.FieldPoints values('Status', 'Status', 'FieldPoint', '30006|2', 'bool', 'false', 'false', 'statusSensors_4',null, null, null, 'ModbusRtuController_4', 'Motor_4')

insert into dbo.FieldPoints values('Current_R', 'Current_R', 'FieldPoint', '30006|2', 'float', 'true', 'false', 'currentSensors_5',null, null, null, 'ModbusRtuController_5', 'Motor_5')
insert into dbo.FieldPoints values('Current_Y', 'Current_Y', 'FieldPoint', '30008|2', 'float', 'true', 'false', 'currentSensors_5',null, null, null, 'ModbusRtuController_5', 'Motor_5')
insert into dbo.FieldPoints values('Current_B', 'Current_B', 'FieldPoint', '30010|2', 'float', 'true', 'false', 'currentSensors_5',null, null, null, 'ModbusRtuController_5', 'Motor_5')
insert into dbo.FieldPoints values('Voltage_1', 'Voltage_1', 'FieldPoint', '30000|2', 'float', 'true', 'false', 'voltageSensors_5',null, null, null, 'ModbusRtuController_5', 'Motor_5')
insert into dbo.FieldPoints values('Voltage_2', 'Voltage_2', 'FieldPoint', '30002|2', 'float', 'true', 'false', 'voltageSensors_5',null, null, null, 'ModbusRtuController_5', 'Motor_5')
insert into dbo.FieldPoints values('Voltage_3', 'Voltage_3', 'FieldPoint', '30004|2', 'float', 'true', 'false', 'voltageSensors_5',null, null, null, 'ModbusRtuController_5', 'Motor_5')
insert into dbo.FieldPoints values('Vibration', 'Vibration', 'FieldPoint', '40000|1', 'float', 'true', 'false', 'vibrationSensors_5', '25', null, null, 'ModbusRtuController_23', 'Motor_5')
insert into dbo.FieldPoints values('Status', 'Status', 'FieldPoint', '30006|2', 'bool', 'false', 'false', 'statusSensors_5',null, null, null, 'ModbusRtuController_5', 'Motor_5')

insert into dbo.FieldPoints values('Current_R', 'Current_R', 'FieldPoint', '30006|2', 'float', 'true', 'false', 'currentSensors_6',null, null, null, 'ModbusRtuController_6', 'Motor_6')
insert into dbo.FieldPoints values('Current_Y', 'Current_Y', 'FieldPoint', '30008|2', 'float', 'true', 'false', 'currentSensors_6',null, null, null, 'ModbusRtuController_6', 'Motor_6')
insert into dbo.FieldPoints values('Current_B', 'Current_B', 'FieldPoint', '30010|2', 'float', 'true', 'false', 'currentSensors_6',null, null, null, 'ModbusRtuController_6', 'Motor_6')
insert into dbo.FieldPoints values('Voltage_1', 'Voltage_1', 'FieldPoint', '30000|2', 'float', 'true', 'false', 'voltageSensors_6',null, null, null, 'ModbusRtuController_6', 'Motor_6')
insert into dbo.FieldPoints values('Voltage_2', 'Voltage_2', 'FieldPoint', '30002|2', 'float', 'true', 'false', 'voltageSensors_6',null, null, null, 'ModbusRtuController_6', 'Motor_6')
insert into dbo.FieldPoints values('Voltage_3', 'Voltage_3', 'FieldPoint', '30004|2', 'float', 'true', 'false', 'voltageSensors_6',null, null, null, 'ModbusRtuController_6', 'Motor_6')
insert into dbo.FieldPoints values('Vibration', 'Vibration', 'FieldPoint', '40000|1', 'float', 'true', 'false', 'vibrationSensors_6', '25', null, null, 'ModbusRtuController_22', 'Motor_6')
insert into dbo.FieldPoints values('Status', 'Status', 'FieldPoint', '30006|2', 'bool', 'false', 'false', 'statusSensors_6',null, null, null, 'ModbusRtuController_6', 'Motor_6')

insert into dbo.FieldPoints values('Current_R', 'Current_R', 'FieldPoint', '30006|2', 'float', 'true', 'false', 'currentSensors_7',null, null, null, 'ModbusRtuController_7', 'Motor_7')
insert into dbo.FieldPoints values('Current_Y', 'Current_Y', 'FieldPoint', '30008|2', 'float', 'true', 'false', 'currentSensors_7',null, null, null, 'ModbusRtuController_7', 'Motor_7')
insert into dbo.FieldPoints values('Current_B', 'Current_B', 'FieldPoint', '30010|2', 'float', 'true', 'false', 'currentSensors_7',null, null, null, 'ModbusRtuController_7', 'Motor_7')
insert into dbo.FieldPoints values('Voltage_1', 'Voltage_1', 'FieldPoint', '30000|2', 'float', 'true', 'false', 'voltageSensors_7',null, null, null, 'ModbusRtuController_7', 'Motor_7')
insert into dbo.FieldPoints values('Voltage_2', 'Voltage_2', 'FieldPoint', '30002|2', 'float', 'true', 'false', 'voltageSensors_7',null, null, null, 'ModbusRtuController_7', 'Motor_7')
insert into dbo.FieldPoints values('Voltage_3', 'Voltage_3', 'FieldPoint', '30004|2', 'float', 'true', 'false', 'voltageSensors_7',null, null, null, 'ModbusRtuController_7', 'Motor_7')
insert into dbo.FieldPoints values('Vibration', 'Vibration', 'FieldPoint', '40000|1', 'float', 'true', 'false', 'vibrationSensors_7', '25', null, null, 'ModbusRtuController_23', 'Motor_7')
insert into dbo.FieldPoints values('Status', 'Status', 'FieldPoint', '30006|2', 'bool', 'false', 'false', 'statusSensors_7',null, null, null, 'ModbusRtuController_7', 'Motor_7')

insert into dbo.FieldPoints values('Current_R', 'Current_R', 'FieldPoint', '30006|2', 'float', 'true', 'false', 'currentSensors_8',null, null, null, 'ModbusRtuController_8', 'Motor_8')
insert into dbo.FieldPoints values('Current_Y', 'Current_Y', 'FieldPoint', '30008|2', 'float', 'true', 'false', 'currentSensors_8',null, null, null, 'ModbusRtuController_8', 'Motor_8')
insert into dbo.FieldPoints values('Current_B', 'Current_B', 'FieldPoint', '30010|2', 'float', 'true', 'false', 'currentSensors_8',null, null, null, 'ModbusRtuController_8', 'Motor_8')
insert into dbo.FieldPoints values('Voltage_1', 'Voltage_1', 'FieldPoint', '30000|2', 'float', 'true', 'false', 'voltageSensors_8',null, null, null, 'ModbusRtuController_8', 'Motor_8')
insert into dbo.FieldPoints values('Voltage_2', 'Voltage_2', 'FieldPoint', '30002|2', 'float', 'true', 'false', 'voltageSensors_8',null, null, null, 'ModbusRtuController_8', 'Motor_8')
insert into dbo.FieldPoints values('Voltage_3', 'Voltage_3', 'FieldPoint', '30004|2', 'float', 'true', 'false', 'voltageSensors_8',null, null, null, 'ModbusRtuController_8', 'Motor_8')
insert into dbo.FieldPoints values('Vibration', 'Vibration', 'FieldPoint', '40000|1', 'float', 'true', 'false', 'vibrationSensors_8', '25', null, null, 'ModbusRtuController_23', 'Motor_8')
insert into dbo.FieldPoints values('Status', 'Status', 'FieldPoint', '30006|2', 'bool', 'false', 'false', 'statusSensors_8',null, null, null, 'ModbusRtuController_8', 'Motor_8')

insert into dbo.FieldPoints values('Current_R', 'Current_R', 'FieldPoint', '30006|2', 'float', 'true', 'false', 'currentSensors_9',null, null, null, 'ModbusRtuController_9', 'Motor_9')
insert into dbo.FieldPoints values('Current_Y', 'Current_Y', 'FieldPoint', '30008|2', 'float', 'true', 'false', 'currentSensors_9',null, null, null, 'ModbusRtuController_9', 'Motor_9')
insert into dbo.FieldPoints values('Current_B', 'Current_B', 'FieldPoint', '30010|2', 'float', 'true', 'false', 'currentSensors_9',null, null, null, 'ModbusRtuController_9', 'Motor_9')
insert into dbo.FieldPoints values('Voltage_1', 'Voltage_1', 'FieldPoint', '30000|2', 'float', 'true', 'false', 'voltageSensors_9',null, null, null, 'ModbusRtuController_9', 'Motor_9')
insert into dbo.FieldPoints values('Voltage_2', 'Voltage_2', 'FieldPoint', '30002|2', 'float', 'true', 'false', 'voltageSensors_9',null, null, null, 'ModbusRtuController_9', 'Motor_9')
insert into dbo.FieldPoints values('Voltage_3', 'Voltage_3', 'FieldPoint', '30004|2', 'float', 'true', 'false', 'voltageSensors_9',null, null, null, 'ModbusRtuController_9', 'Motor_9')
insert into dbo.FieldPoints values('Vibration', 'Vibration', 'FieldPoint', '40000|1', 'float', 'true', 'false', 'vibrationSensors_9', '25', null, null, 'ModbusRtuController_23', 'Motor_9')
insert into dbo.FieldPoints values('Status', 'Status', 'FieldPoint', '30006|2', 'bool', 'false', 'false', 'statusSensors_9',null, null, null, 'ModbusRtuController_9', 'Motor_9')

insert into dbo.FieldPoints values('Current_R', 'Current_R', 'FieldPoint', '30006|2', 'float', 'true', 'false', 'currentSensors_10',null, null, null, 'ModbusRtuController_10', 'Motor_10')
insert into dbo.FieldPoints values('Current_Y', 'Current_Y', 'FieldPoint', '30008|2', 'float', 'true', 'false', 'currentSensors_10',null, null, null, 'ModbusRtuController_10', 'Motor_10')
insert into dbo.FieldPoints values('Current_B', 'Current_B', 'FieldPoint', '30010|2', 'float', 'true', 'false', 'currentSensors_10',null, null, null, 'ModbusRtuController_10', 'Motor_10')
insert into dbo.FieldPoints values('Voltage_1', 'Voltage_1', 'FieldPoint', '30000|2', 'float', 'true', 'false', 'voltageSensors_10',null, null, null, 'ModbusRtuController_10', 'Motor_10')
insert into dbo.FieldPoints values('Voltage_2', 'Voltage_2', 'FieldPoint', '30002|2', 'float', 'true', 'false', 'voltageSensors_10',null, null, null, 'ModbusRtuController_10', 'Motor_10')
insert into dbo.FieldPoints values('Voltage_3', 'Voltage_3', 'FieldPoint', '30004|2', 'float', 'true', 'false', 'voltageSensors_10',null, null, null, 'ModbusRtuController_10', 'Motor_10')
insert into dbo.FieldPoints values('Vibration', 'Vibration', 'FieldPoint', '40000|1', 'float', 'true', 'false', 'vibrationSensors_10', '25', null, null, 'ModbusRtuController_23', 'Motor_10')
insert into dbo.FieldPoints values('Status', 'Status', 'FieldPoint', '30006|2', 'bool', 'false', 'false', 'statusSensors_10',null, null, null, 'ModbusRtuController_10', 'Motor_10')
insert into dbo.FieldPoints values('Status_1', 'Status_1', 'FieldPoint', '30006|2', 'bool', 'false', 'false', 'statusSensors_10',null, null, null, 'ModbusRtuController_10', 'Motor_10')
insert into dbo.FieldPoints values('Status_2', 'Status_2', 'FieldPoint', '30008|2', 'bool', 'false', 'false', 'statusSensors_10',null, null, null, 'ModbusRtuController_10', 'Motor_10')
