use Sunayna
go
  
/* Insert Field devices */
  insert into dbo.FieldDevices values('Motor_1', 'BILGE BALLAST PUMP NO 1', 'AER')
  insert into dbo.FieldDevices values('Motor_2', 'BILGE PUMP 1', 'AER')
  insert into dbo.FieldDevices values('Motor_3', 'AER SUPPLY FAN', 'AER')
  
  insert into dbo.FieldDevices values('Motor_4', 'FIRE MAIN NO 1', 'FER')
  insert into dbo.FieldDevices values('Motor_5', 'BILGE PUMP 2', 'FER')
  insert into dbo.FieldDevices values('Motor_6', 'FER SUPPLY FAN', 'FER')
 
  insert into dbo.FieldDevices values('Motor_7', 'AC PLANT NO 1', 'AMR-1')
  insert into dbo.FieldDevices values('Motor_8', 'AC PLANT NO 2', 'AMR-1')
  insert into dbo.FieldDevices values('Motor_9', 'AC PLANT NO 3', 'AMR-1')
  insert into dbo.FieldDevices values('Motor_10', 'AC CHILLED WATER PUMP NO 1', 'AMR-1')

  insert into dbo.FieldDevices values('Motor_11', 'AC CHILLED WATER PUMP NO 2', 'AMR-2')

  insert into dbo.FieldDevices values('Motor_12', 'AC SEA WATER PUMP NO 1', 'FIN-1')
  insert into dbo.FieldDevices values('Motor_13', 'AC SEA WATER PUMP NO 2', 'FIN-1')
  insert into dbo.FieldDevices values('Motor_14', 'STABILIZER MOTOR (P)', 'FIN-1')
  insert into dbo.FieldDevices values('Motor_15', 'STABILIZER MOTOR (S)', 'FIN-1')

  insert into dbo.FieldDevices values('Motor_16', 'FAN COOLING PUMP (S)', 'FIN-2')
  insert into dbo.FieldDevices values('Motor_17', 'FAN COOLING PUMP (P)', 'FIN-2')
  insert into dbo.FieldDevices values('Motor_18', 'FIRE MAIN NO 2', 'FIN-2')
  insert into dbo.FieldDevices values('Motor_19', 'BILGE BALLAST PUMP NO 2', 'FIN-2')

  insert into dbo.FieldDevices values('Motor_20', 'STEERING GEAR MOTOR (P)', 'ASP')
  insert into dbo.FieldDevices values('Motor_21', 'STEERING GEAR MOTOR (S)', 'ASP')

/* Insert Field Devices and Connected Controllers */
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_1', 'ModbusRtuController_1')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_2', 'ModbusRtuController_2')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_3', 'ModbusRtuController_3')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_4', 'ModbusRtuController_4')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_5', 'ModbusRtuController_5')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_6', 'ModbusRtuController_6')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_7', 'ModbusRtuController_7')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_8', 'ModbusRtuController_8')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_9', 'ModbusRtuController_9')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_10', 'ModbusRtuController_10')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_11', 'ModbusRtuController_11')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_12', 'ModbusRtuController_12')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_13', 'ModbusRtuController_13')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_14', 'ModbusRtuController_14')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_15', 'ModbusRtuController_15')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_16', 'ModbusRtuController_16')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_17', 'ModbusRtuController_17')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_18', 'ModbusRtuController_18')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_19', 'ModbusRtuController_19')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_20', 'ModbusRtuController_20')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_21', 'ModbusRtuController_21')
  
   insert into dbo.FieldDevicesAndConnectedControllers values('Motor_1', 'ModbusRtuController_22')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_2', 'ModbusRtuController_22')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_3', 'ModbusRtuController_22')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_4', 'ModbusRtuController_23')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_5', 'ModbusRtuController_23')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_6', 'ModbusRtuController_23')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_7', 'ModbusRtuController_23')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_8', 'ModbusRtuController_23')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_9', 'ModbusRtuController_23')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_10', 'ModbusRtuController_23')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_11', 'ModbusRtuController_23')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_12', 'ModbusRtuController_24')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_13', 'ModbusRtuController_24')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_14', 'ModbusRtuController_24')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_15', 'ModbusRtuController_24')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_16', 'ModbusRtuController_24')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_17', 'ModbusRtuController_24')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_18', 'ModbusRtuController_24')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_19', 'ModbusRtuController_24')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_20', 'ModbusRtuController_22')
  insert into dbo.FieldDevicesAndConnectedControllers values('Motor_21', 'ModbusRtuController_22')