<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="DisableMaxAndMinAlarms" Id="{b19c8d72-bffd-48d0-9844-45794aaa44ce}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC DisableMaxAndMinAlarms
VAR_INPUT
END_VAR
VAR_OUTPUT
	(* As name suggest force write the Max and Min alarms false *)
	MaxAlarmStatus : BOOL := FALSE;
	MinAlarmStatus : BOOL := FALSE;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="DisableMaxAndMinAlarms">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>