INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('ArmatureBreakerInput', 'ArmatureBreakerInput', 'FieldPoint', '40026|1', 'float', 'true', 'false', 'statusSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('ArmatureSelectorWheelInput', 'ArmatureSelectorWheelInput', 'FieldPoint', '40025|1', 'float', 'true', 'false', 'statusSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('ArmatureSelectorWheelLock', 'ArmatureSelectorWheelLock', 'FieldPoint', '40013|1', 'float', 'false', 'false', 'statusSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('BowArmatureCurrent', 'BowArmatureCurrent', 'FieldPoint', '40003|1', 'float', 'false', 'false', 'analogSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('BowExcitationCurrent', 'BowExcitationCurrent', 'FieldPoint', '40004|1', 'float', 'false', 'false', 'analogSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('ChargeBatteryBank_1', 'ChargeBatteryBank_1', 'FieldPoint', '40000|1', 'float', 'false', 'false', 'analogSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('ChargeBatteryBank_2', 'ChargeBatteryBank_2', 'FieldPoint', '40001|1', 'float', 'false', 'false', 'analogSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('DisChargeBatteryBank_1', 'DisChargeBatteryBank_1', 'FieldPoint', '40005|1', 'float', 'false', 'false', 'analogSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('DisChargeBatteryBank_2', 'DisChargeBatteryBank_2', 'FieldPoint', '40006|1', 'float', 'false', 'false', 'analogSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('EmergencySwitch', 'EmergencySwitch', 'FieldPoint', '40027|1', 'float', 'true', 'false', 'statusSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('GovernorWheelInput', 'GovernorWheelInput', 'FieldPoint', '40029|1', 'float', 'false', 'false', 'speedSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('GrouperControlSwitchModeInput', 'GrouperControlSwitchModeInput', 'FieldPoint', '40021|1', 'float', 'true', 'false', 'statusSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('GrouperControlSwitchSelectionInput', 'GrouperControlSwitchSelectionInput', 'FieldPoint', '40020|1', 'float', 'true', 'false', 'statusSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('MotorStatusIndicator', 'MotorStatusIndicator', 'FieldPoint', '40015|1', 'float', 'false', 'false', 'statusSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('PropulsionWheelInput', 'PropulsionWheelInput', 'FieldPoint', '40023|1', 'float', 'true', 'false', 'statusSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('PropulsionWheelInputLock', 'PropulsionWheelInputLock', 'FieldPoint', '40014|1', 'float', 'false', 'false', 'statusSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('ReverserWheelInput', 'ReverserWheelInput', 'FieldPoint', '40024|1', 'float', 'true', 'false', 'statusSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('ReverserWheelLock', 'ReverserWheelLock', 'FieldPoint', '40012|1', 'float', 'false', 'false', 'statusSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('RPM', 'RPM', 'FieldPoint', '40011|1', 'float', 'true', 'false', 'analogSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('RPMOriginal', 'RPMOriginal', 'FieldPoint', '40002|1', 'float', 'false', 'false', 'analogSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('SternArmatureCurrent', 'SternArmatureCurrent', 'FieldPoint', '40008|1', 'float', 'false', 'false', 'analogSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('SternExcitationCurrent', 'SternExcitationCurrent', 'FieldPoint', '40009|1', 'float', 'false', 'false', 'analogSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('Voltage', 'Voltage', 'FieldPoint', '40007|1', 'float', 'false', 'false', 'analogSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
INSERT dbo.FieldPoints (Label, Description, TypeOfAddress, MemoryAddress, FieldPointDataType, ToBeLogged, RequireNotificationService, SensorDataSetIdentifier, MaxValue, Offset, Multiplier, SourceControllerIdentifier, FieldDeviceIdentifier) VALUES ('VoltmeterSelector', 'VoltmeterSelector', 'FieldPoint', '40019|1', 'float', 'true', 'false', 'statusSensors_1', NULL, NULL, NULL, 'ModbusRtuController_1', 'Motor_1')
GO
