/* Tags for Field Points of Equipments connected to Reactor */
delete from dbo.FieldPoints

/* Tags for Reactor 1 */
	insert into dbo.FieldPoints values('UsedNow', 'Reactor_1|UsedNow', 'FieldPoint', 'R1.UsedNow', 'bool', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('RunningBatchStatus', 'RunningBatchStatus', 'FieldPoint', 'R1.RunningBatchStatus', 'bool', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('HeatCoolStatus', 'HeatCoolStatus', 'FieldPoint', 'R1.HeatCoolStatus', 'bool', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('HeatCoolSetPoint', 'HeatCoolSetPoint', 'FieldPoint', 'R1.HeatCoolSetPoint', 'int', 'true', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('HeatCoolStatusFeedback', 'HeatCoolStatusFeedback', 'FieldPoint', 'R1.HeatCoolStatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('HeatCoolTemperatureControl', 'HeatCoolTemperatureControl', 'FieldPoint', 'R1.HeatCoolTemperatureControlType', 'bool', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('HeatCoolFailure', 'HeatCoolFailure', 'FieldPoint', 'R1.HeatCoolFailure', 'bool', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('StirrerStatus', 'StirrerStatus', 'FieldPoint', 'R1.StirrerStatus', 'bool', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('StirrerSpeedSetPoint', 'StirrerSpeedSetPoint', 'FieldPoint', 'R1.StirrerSetPoint', 'int', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('StirrerStatusFeedback', 'StirrerStatusFeedback', 'FieldPoint', 'R1.StirrerStatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('StirrerCurrentSpeed', 'StirrerCurrentSpeed', 'FieldPoint', 'R1.StirrerCurrentSpeed', 'int', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('StirrerFailure', 'StirrerFailure', 'FieldPoint', 'R1.StirrerFailure', 'bool', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('ReactorMassTemperature', 'ReactorMassTemperature', 'FieldPoint', 'R1.ReactorMassTemperature', 'float', 'true', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Pressure', 'Pressure', 'FieldPoint', 'R1.Pressure', 'float', 'true', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('PHvalue', 'PHvalue', 'FieldPoint', 'R1.PHvalue', 'float', 'true', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('RPM', 'RPM', 'FieldPoint', 'R1.StirrerCurrentSpeed', 'int', 'true', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('JacketOutletTemperature', 'JacketOutletTemperature', 'FieldPoint', 'R1.JacketOutletTemperature', 'float', 'true', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('EmergencyStatus', 'EmergencyStatus', 'FieldPoint', 'R1.EmergencyStatus', 'bool', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('DosingPumpStatus', 'DosingPumpStatus', 'FieldPoint', 'R1.DosingPumpStatus_1', 'bool', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('DosingPumpFlowSetPoint', 'DosingPumpFlowSetPoint', 'FieldPoint', 'R1.DosingPumpSetPoint_1', 'float', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('DosingPumpStatusFeedback', 'DosingPumpStatusFeedback', 'FieldPoint', 'R1.DosingPumpStatusFeedback_1', 'bool', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('DosingPumpCurrentFlow', 'DosingPumpCurrentFlow', 'FieldPoint', 'R1.DosingPumpCurrentDosingFlow_1', 'float', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('BatchName', 'BatchName', 'FieldPoint', 'R1.BatchText_1', 'string', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('BatchNumber', 'BatchNumber', 'FieldPoint', 'R1.BatchText_2', 'string', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('BatchRemarks', 'BatchRemarks', 'FieldPoint', 'R1.BatchText_3', 'string', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('BatchStatus', 'BatchStatus', 'FieldPoint', 'R1.BatchText_4', 'string', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('BatchScientistName', 'BatchScientistName', 'FieldPoint', 'R1.BatchText_5', 'string', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	
/* Tags for Reactor 2 */
	insert into dbo.FieldPoints values('UsedNow', 'Reactor_2|UsedNow', 'FieldPoint', 'R2.UsedNow', 'bool', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('RunningBatchStatus', 'RunningBatchStatus', 'FieldPoint', 'R2.RunningBatchStatus', 'bool', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('HeatCoolStatus', 'HeatCoolStatus', 'FieldPoint', 'R2.HeatCoolStatus', 'bool', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('HeatCoolSetPoint', 'HeatCoolSetPoint', 'FieldPoint', 'R2.HeatCoolSetPoint', 'int', 'true', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('HeatCoolStatusFeedback', 'HeatCoolStatusFeedback', 'FieldPoint', 'R2.HeatCoolStatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('HeatCoolTemperatureControl', 'HeatCoolTemperatureControl', 'FieldPoint', 'R2.HeatCoolTemperatureControlType', 'bool', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('HeatCoolFailure', 'HeatCoolFailure', 'FieldPoint', 'R2.HeatCoolFailure', 'bool', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('StirrerStatus', 'StirrerStatus', 'FieldPoint', 'R2.StirrerStatus', 'bool', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('StirrerSpeedSetPoint', 'StirrerSpeedSetPoint', 'FieldPoint', 'R2.StirrerSetPoint', 'int', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('StirrerStatusFeedback', 'StirrerStatusFeedback', 'FieldPoint', 'R2.StirrerStatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('StirrerCurrentSpeed', 'StirrerCurrentSpeed', 'FieldPoint', 'R2.StirrerCurrentSpeed', 'int', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('StirrerFailure', 'StirrerFailure', 'FieldPoint', 'R2.StirrerFailure', 'bool', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('ReactorMassTemperature', 'ReactorMassTemperature', 'FieldPoint', 'R2.ReactorMassTemperature', 'float', 'true', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('Pressure', 'Pressure', 'FieldPoint', 'R2.Pressure', 'float', 'true', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('PHvalue', 'PHvalue', 'FieldPoint', 'R2.PHvalue', 'float', 'true', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('RPM', 'RPM', 'FieldPoint', 'R2.StirrerCurrentSpeed', 'int', 'true', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('JacketOutletTemperature', 'JacketOutletTemperature', 'FieldPoint', 'R2.JacketOutletTemperature', 'float', 'true', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('EmergencyStatus', 'EmergencyStatus', 'FieldPoint', 'R2.EmergencyStatus', 'bool', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('DosingPumpStatus', 'DosingPumpStatus', 'FieldPoint', 'R2.DosingPumpStatus_1', 'bool', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('DosingPumpFlowSetPoint', 'DosingPumpFlowSetPoint', 'FieldPoint', 'R2.DosingPumpSetPoint_1', 'float', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('DosingPumpStatusFeedback', 'DosingPumpStatusFeedback', 'FieldPoint', 'R2.DosingPumpStatusFeedback_1', 'bool', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('DosingPumpCurrentFlow', 'DosingPumpCurrentFlow', 'FieldPoint', 'R2.DosingPumpCurrentDosingFlow_1', 'float', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('BatchName', 'BatchName', 'FieldPoint', 'R2.BatchText_1', 'string', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('BatchNumber', 'BatchNumber', 'FieldPoint', 'R2.BatchText_2', 'string', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('BatchRemarks', 'BatchRemarks', 'FieldPoint', 'R2.BatchText_3', 'string', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('BatchStatus', 'BatchStatus', 'FieldPoint', 'R2.BatchText_4', 'string', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	insert into dbo.FieldPoints values('BatchScientistName', 'BatchScientistName', 'FieldPoint', 'R2.BatchText_5', 'string', 'false', 'true', 'sensorDataSet_2', 'Reactor_2')
	
/* Tags for Reactor 3 */
	insert into dbo.FieldPoints values('UsedNow', 'Reactor_3|UsedNow', 'FieldPoint', 'R3.UsedNow', 'bool', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('RunningBatchStatus', 'RunningBatchStatus', 'FieldPoint', 'R3.RunningBatchStatus', 'bool', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('HeatCoolStatus', 'HeatCoolStatus', 'FieldPoint', 'R3.HeatCoolStatus', 'bool', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('HeatCoolSetPoint', 'HeatCoolSetPoint', 'FieldPoint', 'R3.HeatCoolSetPoint', 'int', 'true', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('HeatCoolStatusFeedback', 'HeatCoolStatusFeedback', 'FieldPoint', 'R3.HeatCoolStatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('HeatCoolTemperatureControl', 'HeatCoolTemperatureControl', 'FieldPoint', 'R3.HeatCoolTemperatureControlType', 'bool', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('HeatCoolFailure', 'HeatCoolFailure', 'FieldPoint', 'R3.HeatCoolFailure', 'bool', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('StirrerStatus', 'StirrerStatus', 'FieldPoint', 'R3.StirrerStatus', 'bool', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('StirrerSpeedSetPoint', 'StirrerSpeedSetPoint', 'FieldPoint', 'R3.StirrerSetPoint', 'int', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('StirrerStatusFeedback', 'StirrerStatusFeedback', 'FieldPoint', 'R3.StirrerStatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('StirrerCurrentSpeed', 'StirrerCurrentSpeed', 'FieldPoint', 'R3.StirrerCurrentSpeed', 'int', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('StirrerFailure', 'StirrerFailure', 'FieldPoint', 'R3.StirrerFailure', 'bool', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('ReactorMassTemperature', 'ReactorMassTemperature', 'FieldPoint', 'R3.ReactorMassTemperature', 'float', 'true', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('Pressure', 'Pressure', 'FieldPoint', 'R3.Pressure', 'float', 'true', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('PHvalue', 'PHvalue', 'FieldPoint', 'R3.PHvalue', 'float', 'true', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('RPM', 'RPM', 'FieldPoint', 'R3.StirrerCurrentSpeed', 'int', 'true', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('JacketOutletTemperature', 'JacketOutletTemperature', 'FieldPoint', 'R3.JacketOutletTemperature', 'float', 'true', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('EmergencyStatus', 'EmergencyStatus', 'FieldPoint', 'R3.EmergencyStatus', 'bool', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('DosingPumpStatus', 'DosingPumpStatus', 'FieldPoint', 'R3.DosingPumpStatus_1', 'bool', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('DosingPumpFlowSetPoint', 'DosingPumpFlowSetPoint', 'FieldPoint', 'R3.DosingPumpSetPoint_1', 'float', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('DosingPumpStatusFeedback', 'DosingPumpStatusFeedback', 'FieldPoint', 'R3.DosingPumpStatusFeedback_1', 'bool', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('DosingPumpCurrentFlow', 'DosingPumpCurrentFlow', 'FieldPoint', 'R3.DosingPumpCurrentDosingFlow_1', 'float', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('BatchName', 'BatchName', 'FieldPoint', 'R3.BatchText_1', 'string', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('BatchNumber', 'BatchNumber', 'FieldPoint', 'R3.BatchText_2', 'string', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('BatchRemarks', 'BatchRemarks', 'FieldPoint', 'R3.BatchText_3', 'string', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('BatchStatus', 'BatchStatus', 'FieldPoint', 'R3.BatchText_4', 'string', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	insert into dbo.FieldPoints values('BatchScientistName', 'BatchScientistName', 'FieldPoint', 'R3.BatchText_5', 'string', 'false', 'true', 'sensorDataSet_3', 'Reactor_3')
	
/* Tags for Reactor 4 */
	insert into dbo.FieldPoints values('UsedNow', 'Reactor_4|UsedNow', 'FieldPoint', 'R4.UsedNow', 'bool', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('RunningBatchStatus', 'RunningBatchStatus', 'FieldPoint', 'R4.RunningBatchStatus', 'bool', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('HeatCoolStatus', 'HeatCoolStatus', 'FieldPoint', 'R4.HeatCoolStatus', 'bool', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('HeatCoolSetPoint', 'HeatCoolSetPoint', 'FieldPoint', 'R4.HeatCoolSetPoint', 'int', 'true', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('HeatCoolStatusFeedback', 'HeatCoolStatusFeedback', 'FieldPoint', 'R4.HeatCoolStatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('HeatCoolTemperatureControl', 'HeatCoolTemperatureControl', 'FieldPoint', 'R4.HeatCoolTemperatureControlType', 'bool', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('HeatCoolFailure', 'HeatCoolFailure', 'FieldPoint', 'R4.HeatCoolFailure', 'bool', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('StirrerStatus', 'StirrerStatus', 'FieldPoint', 'R4.StirrerStatus', 'bool', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('StirrerSpeedSetPoint', 'StirrerSpeedSetPoint', 'FieldPoint', 'R4.StirrerSetPoint', 'int', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('StirrerStatusFeedback', 'StirrerStatusFeedback', 'FieldPoint', 'R4.StirrerStatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('StirrerCurrentSpeed', 'StirrerCurrentSpeed', 'FieldPoint', 'R4.StirrerCurrentSpeed', 'int', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('StirrerFailure', 'StirrerFailure', 'FieldPoint', 'R4.StirrerFailure', 'bool', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('ReactorMassTemperature', 'ReactorMassTemperature', 'FieldPoint', 'R4.ReactorMassTemperature', 'float', 'true', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('Pressure', 'Pressure', 'FieldPoint', 'R4.Pressure', 'float', 'true', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('PHvalue', 'PHvalue', 'FieldPoint', 'R4.PHvalue', 'float', 'true', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('RPM', 'RPM', 'FieldPoint', 'R4.StirrerCurrentSpeed', 'int', 'true', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('JacketOutletTemperature', 'JacketOutletTemperature', 'FieldPoint', 'R4.JacketOutletTemperature', 'float', 'true', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('EmergencyStatus', 'EmergencyStatus', 'FieldPoint', 'R4.EmergencyStatus', 'bool', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('DosingPumpStatus', 'DosingPumpStatus', 'FieldPoint', 'R4.DosingPumpStatus_1', 'bool', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('DosingPumpFlowSetPoint', 'DosingPumpFlowSetPoint', 'FieldPoint', 'R4.DosingPumpSetPoint_1', 'float', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('DosingPumpStatusFeedback', 'DosingPumpStatusFeedback', 'FieldPoint', 'R4.DosingPumpStatusFeedback_1', 'bool', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('DosingPumpCurrentFlow', 'DosingPumpCurrentFlow', 'FieldPoint', 'R4.DosingPumpCurrentDosingFlow_1', 'float', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('BatchName', 'BatchName', 'FieldPoint', 'R4.BatchText_1', 'string', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('BatchNumber', 'BatchNumber', 'FieldPoint', 'R4.BatchText_2', 'string', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('BatchRemarks', 'BatchRemarks', 'FieldPoint', 'R4.BatchText_3', 'string', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('BatchStatus', 'BatchStatus', 'FieldPoint', 'R4.BatchText_4', 'string', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	insert into dbo.FieldPoints values('BatchScientistName', 'BatchScientistName', 'FieldPoint', 'R4.BatchText_5', 'string', 'false', 'true', 'sensorDataSet_4', 'Reactor_4')
	
/* Tags for Reactor 5 */
	insert into dbo.FieldPoints values('UsedNow', 'Reactor_5|UsedNow', 'FieldPoint', 'R5.UsedNow', 'bool', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('RunningBatchStatus', 'RunningBatchStatus', 'FieldPoint', 'R5.RunningBatchStatus', 'bool', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('HeatCoolStatus', 'HeatCoolStatus', 'FieldPoint', 'R5.HeatCoolStatus', 'bool', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('HeatCoolSetPoint', 'HeatCoolSetPoint', 'FieldPoint', 'R5.HeatCoolSetPoint', 'int', 'true', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('HeatCoolStatusFeedback', 'HeatCoolStatusFeedback', 'FieldPoint', 'R5.HeatCoolStatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('HeatCoolTemperatureControl', 'HeatCoolTemperatureControl', 'FieldPoint', 'R5.HeatCoolTemperatureControlType', 'bool', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('HeatCoolFailure', 'HeatCoolFailure', 'FieldPoint', 'R5.HeatCoolFailure', 'bool', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('StirrerStatus', 'StirrerStatus', 'FieldPoint', 'R5.StirrerStatus', 'bool', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('StirrerSpeedSetPoint', 'StirrerSpeedSetPoint', 'FieldPoint', 'R5.StirrerSetPoint', 'int', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('StirrerStatusFeedback', 'StirrerStatusFeedback', 'FieldPoint', 'R5.StirrerStatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('StirrerCurrentSpeed', 'StirrerCurrentSpeed', 'FieldPoint', 'R5.StirrerCurrentSpeed', 'int', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('StirrerFailure', 'StirrerFailure', 'FieldPoint', 'R5.StirrerFailure', 'bool', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('ReactorMassTemperature', 'ReactorMassTemperature', 'FieldPoint', 'R5.ReactorMassTemperature', 'float', 'true', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('Pressure', 'Pressure', 'FieldPoint', 'R5.Pressure', 'float', 'true', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('PHvalue', 'PHvalue', 'FieldPoint', 'R5.PHvalue', 'float', 'true', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('RPM', 'RPM', 'FieldPoint', 'R5.StirrerCurrentSpeed', 'int', 'true', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('JacketOutletTemperature', 'JacketOutletTemperature', 'FieldPoint', 'R5.JacketOutletTemperature', 'float', 'true', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('EmergencyStatus', 'EmergencyStatus', 'FieldPoint', 'R5.EmergencyStatus', 'bool', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('DosingPumpStatus', 'DosingPumpStatus', 'FieldPoint', 'R5.DosingPumpStatus_1', 'bool', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('DosingPumpFlowSetPoint', 'DosingPumpFlowSetPoint', 'FieldPoint', 'R5.DosingPumpSetPoint_1', 'float', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('DosingPumpStatusFeedback', 'DosingPumpStatusFeedback', 'FieldPoint', 'R5.DosingPumpStatusFeedback_1', 'bool', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('DosingPumpCurrentFlow', 'DosingPumpCurrentFlow', 'FieldPoint', 'R5.DosingPumpCurrentDosingFlow_1', 'float', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('BatchName', 'BatchName', 'FieldPoint', 'R5.BatchText_1', 'string', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('BatchNumber', 'BatchNumber', 'FieldPoint', 'R5.BatchText_2', 'string', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('BatchRemarks', 'BatchRemarks', 'FieldPoint', 'R5.BatchText_3', 'string', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('BatchStatus', 'BatchStatus', 'FieldPoint', 'R5.BatchText_4', 'string', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	insert into dbo.FieldPoints values('BatchScientistName', 'BatchScientistName', 'FieldPoint', 'R5.BatchText_5', 'string', 'false', 'true', 'sensorDataSet_5', 'Reactor_5')
	
/* Tags for Reactor 6 */
	insert into dbo.FieldPoints values('UsedNow', 'Reactor_6|UsedNow', 'FieldPoint', 'R6.UsedNow', 'bool', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('RunningBatchStatus', 'RunningBatchStatus', 'FieldPoint', 'R6.RunningBatchStatus', 'bool', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('HeatCoolStatus', 'HeatCoolStatus', 'FieldPoint', 'R6.HeatCoolStatus', 'bool', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('HeatCoolSetPoint', 'HeatCoolSetPoint', 'FieldPoint', 'R6.HeatCoolSetPoint', 'int', 'true', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('HeatCoolStatusFeedback', 'HeatCoolStatusFeedback', 'FieldPoint', 'R6.HeatCoolStatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('HeatCoolTemperatureControl', 'HeatCoolTemperatureControl', 'FieldPoint', 'R6.HeatCoolTemperatureControlType', 'bool', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('HeatCoolFailure', 'HeatCoolFailure', 'FieldPoint', 'R6.HeatCoolFailure', 'bool', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('StirrerStatus', 'StirrerStatus', 'FieldPoint', 'R6.StirrerStatus', 'bool', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('StirrerSpeedSetPoint', 'StirrerSpeedSetPoint', 'FieldPoint', 'R6.StirrerSetPoint', 'int', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('StirrerStatusFeedback', 'StirrerStatusFeedback', 'FieldPoint', 'R6.StirrerStatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('StirrerCurrentSpeed', 'StirrerCurrentSpeed', 'FieldPoint', 'R6.StirrerCurrentSpeed', 'int', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('StirrerFailure', 'StirrerFailure', 'FieldPoint', 'R6.StirrerFailure', 'bool', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('ReactorMassTemperature', 'ReactorMassTemperature', 'FieldPoint', 'R6.ReactorMassTemperature', 'float', 'true', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('Pressure', 'Pressure', 'FieldPoint', 'R6.Pressure', 'float', 'true', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('PHvalue', 'PHvalue', 'FieldPoint', 'R6.PHvalue', 'float', 'true', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('RPM', 'RPM', 'FieldPoint', 'R6.StirrerCurrentSpeed', 'int', 'true', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('JacketOutletTemperature', 'JacketOutletTemperature', 'FieldPoint', 'R6.JacketOutletTemperature', 'float', 'true', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('EmergencyStatus', 'EmergencyStatus', 'FieldPoint', 'R6.EmergencyStatus', 'bool', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('DosingPumpStatus', 'DosingPumpStatus', 'FieldPoint', 'R6.DosingPumpStatus_1', 'bool', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('DosingPumpFlowSetPoint', 'DosingPumpFlowSetPoint', 'FieldPoint', 'R6.DosingPumpSetPoint_1', 'float', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('DosingPumpStatusFeedback', 'DosingPumpStatusFeedback', 'FieldPoint', 'R6.DosingPumpStatusFeedback_1', 'bool', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('DosingPumpCurrentFlow', 'DosingPumpCurrentFlow', 'FieldPoint', 'R6.DosingPumpCurrentDosingFlow_1', 'float', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('BatchName', 'BatchName', 'FieldPoint', 'R6.BatchText_1', 'string', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('BatchNumber', 'BatchNumber', 'FieldPoint', 'R6.BatchText_2', 'string', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('BatchRemarks', 'BatchRemarks', 'FieldPoint', 'R6.BatchText_3', 'string', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('BatchStatus', 'BatchStatus', 'FieldPoint', 'R6.BatchText_4', 'string', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	insert into dbo.FieldPoints values('BatchScientistName', 'BatchScientistName', 'FieldPoint', 'R6.BatchText_5', 'string', 'false', 'true', 'sensorDataSet_6', 'Reactor_6')
	
/* Tags for Chiller 6 TR */
	insert into dbo.FieldPoints values('UsedNow', '6TR_Chiller|UsedNow', 'FieldPoint', 'Chiller.UsedNow_6TR', 'bool', 'false', 'true', 'sensorDataSet_7', '6TR_Chiller')
	insert into dbo.FieldPoints values('PressureSwitchStatus', 'PressureSwitchStatus', 'FieldPoint', 'Chiller.PressureSwitch_6TR', 'bool', 'false', 'true', 'sensorDataSet_7', '6TR_Chiller')
    insert into dbo.FieldPoints values('FlowSwitchStatus', 'FlowSwitchStatus', 'FieldPoint', 'Chiller.FlowSwitch_6TR', 'bool', 'false', 'true', 'sensorDataSet_7', '6TR_Chiller')
    insert into dbo.FieldPoints values('HighLevelSwitchStatus', 'HighLevelSwitchStatus', 'FieldPoint', 'Chiller.HighLevel_6TR', 'bool', 'false', 'true', 'sensorDataSet_7', '6TR_Chiller')
    insert into dbo.FieldPoints values('LowLevelSwitchStatus', 'LowLevelSwitchStatus', 'FieldPoint', 'Chiller.LowLevel_6TR', 'bool', 'false', 'true', 'sensorDataSet_7', '6TR_Chiller')
    insert into dbo.FieldPoints values('HppStatusFeedback', 'HppStatusFeedback', 'FieldPoint', 'Chiller.HppStatusFeedback_6TR', 'bool', 'false', 'true', 'sensorDataSet_7', '6TR_Chiller')
    insert into dbo.FieldPoints values('HppTripStatus', 'HppTripStatus', 'FieldPoint', 'Chiller.HppTrip_6TR', 'bool', 'false', 'true', 'sensorDataSet_7', '6TR_Chiller')
    insert into dbo.FieldPoints values('HeatCoolChilledTemperature', 'HeatCoolChilledTemperature', 'FieldPoint', 'Chiller.HuberChilledTemp_6TR', 'float', 'false', 'true', 'sensorDataSet_7', '6TR_Chiller')
    insert into dbo.FieldPoints values('CondenserChilledTemperature', 'CondenserChilledTemperature', 'FieldPoint', 'Chiller.CondenserChilledTemp_6TR', 'float', 'false', 'true', 'sensorDataSet_7', '6TR_Chiller')
    insert into dbo.FieldPoints values('CppStatus', 'CppStatus', 'FieldPoint', 'Chiller.CppStatus_6TR', 'bool', 'false', 'true', 'sensorDataSet_7', '6TR_Chiller')
    insert into dbo.FieldPoints values('HppStatus', 'HppStatus', 'FieldPoint', 'Chiller.HppStatus_6TR', 'bool', 'false', 'true', 'sensorDataSet_7', '6TR_Chiller')
    insert into dbo.FieldPoints values('CoolingSovStatus', 'CoolingSovStatus', 'FieldPoint', 'Chiller.CoolingSovStatus_6TR', 'bool', 'false', 'true', 'sensorDataSet_7', '6TR_Chiller')
	
	insert into dbo.FieldPoints values('TraneChillerStatus', 'TraneChillerStatus', 'FieldPoint', 'OtherEquipment.TraneChillerStatus', 'bool', 'false', 'true', 'sensorDataSet_7', '6TR_Chiller')
	insert into dbo.FieldPoints values('TraneChillerStatusFeedback', 'TraneChillerStatusFeedback', 'FieldPoint', 'OtherEquipment.TraneChillerStatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_7', '6TR_Chiller')
	insert into dbo.FieldPoints values('TraneChillerCurrentTemperature', 'TraneChillerCurrentTemperature', 'FieldPoint', 'OtherEquipment.TraneChillerCurrentTemperature', 'int', 'false', 'true', 'sensorDataSet_7', '6TR_Chiller')

/* Tags for Chiller 10 TR */
	insert into dbo.FieldPoints values('UsedNow', '10TR_Chiller|UsedNow', 'FieldPoint', 'Chiller.UsedNow_10TR', 'bool', 'false', 'true', 'sensorDataSet_8', '10TR_Chiller')
	insert into dbo.FieldPoints values('PressureSwitchStatus', 'PressureSwitchStatus', 'FieldPoint', 'Chiller.PressureSwitch_10TR', 'bool', 'false', 'true', 'sensorDataSet_8', '10TR_Chiller')
    insert into dbo.FieldPoints values('FlowSwitchStatus', 'FlowSwitchStatus', 'FieldPoint', 'Chiller.FlowSwitch_10TR', 'bool', 'false', 'true', 'sensorDataSet_8', '10TR_Chiller')
    insert into dbo.FieldPoints values('HighLevelSwitchStatus', 'HighLevelSwitchStatus', 'FieldPoint', 'Chiller.HighLevel_10TR', 'bool', 'false', 'true', 'sensorDataSet_8', '10TR_Chiller')
    insert into dbo.FieldPoints values('LowLevelSwitchStatus', 'LowLevelSwitchStatus', 'FieldPoint', 'Chiller.LowLevel_10TR', 'bool', 'false', 'true', 'sensorDataSet_8', '10TR_Chiller')
    insert into dbo.FieldPoints values('HppStatusFeedback', 'HppStatusFeedback', 'FieldPoint', 'Chiller.HppStatusFeedback_10TR', 'bool', 'false', 'true', 'sensorDataSet_8', '10TR_Chiller')
    insert into dbo.FieldPoints values('HppTripStatus', 'HppTripStatus', 'FieldPoint', 'Chiller.HppTrip_10TR', 'bool', 'false', 'true', 'sensorDataSet_8', '10TR_Chiller')
    insert into dbo.FieldPoints values('HeatCoolChilledTemperature', 'HeatCoolChilledTemperature', 'FieldPoint', 'Chiller.HuberChilledTemp_10TR', 'float', 'false', 'true', 'sensorDataSet_8', '10TR_Chiller')
    insert into dbo.FieldPoints values('CondenserChilledTemperature', 'CondenserChilledTemperature', 'FieldPoint', 'Chiller.CondenserChilledTemp_10TR', 'float', 'false', 'true', 'sensorDataSet_8', '10TR_Chiller')
    insert into dbo.FieldPoints values('CppStatus', 'CppStatus', 'FieldPoint', 'Chiller.CppStatus_10TR', 'bool', 'false', 'true', 'sensorDataSet_8', '10TR_Chiller')
    insert into dbo.FieldPoints values('HppStatus', 'HppStatus', 'FieldPoint', 'Chiller.HppStatus_10TR', 'bool', 'false', 'true', 'sensorDataSet_8', '10TR_Chiller')
    insert into dbo.FieldPoints values('CoolingSovStatus', 'CoolingSovStatus', 'FieldPoint', 'Chiller.CoolingSovStatus_10TR', 'bool', 'false', 'true', 'sensorDataSet_8', '10TR_Chiller')
	
	insert into dbo.FieldPoints values('TraneChillerStatus', 'TraneChillerStatus', 'FieldPoint', 'OtherEquipment.TraneChillerStatus', 'bool', 'false', 'true', 'sensorDataSet_8', '10TR_Chiller')
	insert into dbo.FieldPoints values('TraneChillerStatusFeedback', 'TraneChillerStatusFeedback', 'FieldPoint', 'OtherEquipment.TraneChillerStatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_8', '10TR_Chiller')
	insert into dbo.FieldPoints values('TraneChillerCurrentTemperature', 'TraneChillerCurrentTemperature', 'FieldPoint', 'OtherEquipment.TraneChillerCurrentTemperature', 'int', 'false', 'true', 'sensorDataSet_8', '10TR_Chiller')

/* Tags for Other Equpiment */
	insert into dbo.FieldPoints values('CameraStatus', 'CameraStatus', 'FieldPoint', 'MAIN.CameraStatus', 'bool', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('LampStatus', 'LampStatus', 'FieldPoint', 'MAIN.LampStatus', 'bool', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')

	insert into dbo.FieldPoints values('UsedNow', 'OtherEquipment|UsedNow', 'FieldPoint', 'OtherEquipment.UsedNow', 'bool', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('AnfdStatus', 'AnfdStatus', 'FieldPoint', 'OtherEquipment.anfdStatus', 'bool', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('AnfdCurrentTemperature', 'AnfdCurrentTemperature', 'FieldPoint', 'OtherEquipment.anfdCurrentTemperature', 'float',  'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('RcvdStatus', 'RcvdStatus', 'FieldPoint', 'OtherEquipment.rcvdStatus', 'bool',  'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('RcvdCurrentSpeed', 'RcvdCurrentSpeed', 'FieldPoint', 'OtherEquipment.rcvdCurrentSpeed', 'int',  'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('PinmillStatus', 'PinmillStatus', 'FieldPoint', 'OtherEquipment.pinmillStatus', 'bool',  'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('JetmillStatus', 'JetmillStatus', 'FieldPoint', 'OtherEquipment.jetmillStatus', 'bool',  'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('RotavapourStatus', 'RotavapourStatus', 'FieldPoint', 'OtherEquipment.rotavapourStatus', 'bool',  'false', 'true', 'sensorDataSet_9', 'OtherEquipment')

	insert into dbo.FieldPoints values('CentrifugeStatus', 'CentrifugeStatus', 'FieldPoint', 'OtherEquipment.centrifugeStatus', 'bool',  'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('CentrifugeStatusFeedback', 'CentrifugeStatusFeedback', 'FieldPoint', 'OtherEquipment.centrifugeStatusFeedback', 'bool',  'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('CentrifugeSpeedSetPoint', 'CentrifugeSpeedSetPoint', 'FieldPoint', 'OtherEquipment.centrifugeSpeedSetPoint', 'int',  'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('CentrifugeCurrentSpeed', 'CentrifugeCurrentSpeed', 'FieldPoint', 'OtherEquipment.centrifugeCurrentSpeed', 'int',  'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('CentrifugeTripStatusFeedback', 'CentrifugeTripStatusFeedback', 'FieldPoint', 'OtherEquipment.CentrifugeTripFeedback', 'bool',  'false', 'true', 'sensorDataSet_9', 'OtherEquipment')

	insert into dbo.FieldPoints values('Scrubber_1_Status', 'Scrubber_1_Status', 'FieldPoint', 'OtherEquipment.Scrubber_1_Status', 'bool', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('Scrubber_1_StatusFeedback', 'Scrubber_1_StatusFeedback', 'FieldPoint', 'OtherEquipment.Scrubber_1_StatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('Scrubber_1_TripStatusFeedback', 'Scrubber_1_TripStatusFeedback', 'FieldPoint', 'OtherEquipment.Scrubber_1_TripStatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	
	insert into dbo.FieldPoints values('Scrubber_2_Status', 'Scrubber_2_Status', 'FieldPoint', 'OtherEquipment.Scrubber_2_Status', 'bool', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('Scrubber_2_StatusFeedback', 'Scrubber_2_StatusFeedback', 'FieldPoint', 'OtherEquipment.Scrubber_2_StatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('Scrubber_2_TripStatusFeedback', 'Scrubber_2_TripStatusFeedback', 'FieldPoint', 'OtherEquipment.Scrubber_2_TripStatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')

	insert into dbo.FieldPoints values('Scrubber_3_Status', 'Scrubber_3_Status', 'FieldPoint', 'OtherEquipment.Scrubber_3_Status', 'bool', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('Scrubber_3_StatusFeedback', 'Scrubber_3_StatusFeedback', 'FieldPoint', 'OtherEquipment.Scrubber_3_StatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('Scrubber_3_TripStatusFeedback', 'Scrubber_3_TripStatusFeedback', 'FieldPoint', 'OtherEquipment.Scrubber_3_TripStatusFeedback', 'bool', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')

	insert into dbo.FieldPoints values('AhuStatus', 'AhuStatus', 'FieldPoint' ,'OtherEquipment.AhuStatus', 'bool', 'false' ,'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('AhuStatusFeedback', 'AhuStatusFeedback', 'FieldPoint' ,'OtherEquipment.AhuStatusFeedback', 'bool', 'false' ,'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('AhuTripStatusFeedback', 'AhuTripStatusFeedback', 'FieldPoint' ,'OtherEquipment.AhuTripStatusFeedback', 'bool', 'false' ,'true', 'sensorDataSet_9', 'OtherEquipment')
	
	insert into dbo.FieldPoints values('Anfd_PowerConsumption', 'Anfd_PowerConsumption', 'EquipmentUsageTracker', 'OtherEquipment.AnfdPowerConsumption', 'float', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('Anfd_NumberOfHoursUsed', 'Anfd_NumberOfHoursUsed', 'EquipmentUsageTracker', 'OtherEquipment.AnfdNumberOfHoursUsed', 'float', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')

	insert into dbo.FieldPoints values('Rcvd_PowerConsumption', 'Rcvd_PowerConsumption', 'EquipmentUsageTracker', 'OtherEquipment.RcvdPowerConsumption', 'float', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('Rcvd_NumberOfHoursUsed', 'Rcvd_NumberOfHoursUsed', 'EquipmentUsageTracker', 'OtherEquipment.RcvdNumberOfHoursUsed', 'float', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')

	insert into dbo.FieldPoints values('Pinmill_PowerConsumption', 'Pinmill_PowerConsumption', 'EquipmentUsageTracker', 'OtherEquipment.PinmillPowerConsumption', 'float', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('Pinmill_NumberOfHoursUsed', 'Pinmill_NumberOfHoursUsed', 'EquipmentUsageTracker', 'OtherEquipment.PinmillNumberOfHoursUsed', 'float', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')

	insert into dbo.FieldPoints values('Jetmill_PowerConsumption', 'Jetmill_PowerConsumption', 'EquipmentUsageTracker', 'OtherEquipment.JetmillPowerConsumption', 'float', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('Jetmill_NumberOfHoursUsed', 'Jetmill_NumberOfHoursUsed', 'EquipmentUsageTracker', 'OtherEquipment.JetmillNumberOfHoursUsed', 'float', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')

	insert into dbo.FieldPoints values('RotaVapour_PowerConsumption', 'RotaVapour_PowerConsumption', 'EquipmentUsageTracker', 'OtherEquipment.RotaVapourPowerConsumption', 'float', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('RotaVapour_NumberOfHoursUsed', 'RotaVapour_NumberOfHoursUsed', 'EquipmentUsageTracker', 'OtherEquipment.RotaVapourNumberOfHoursUsed', 'float', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')

	insert into dbo.FieldPoints values('Centrifuge_PowerConsumption', 'Centrifuge_PowerConsumption', 'EquipmentUsageTracker', 'OtherEquipment.CentrifugePowerConsumption', 'float', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')
	insert into dbo.FieldPoints values('Centrifuge_NumberOfHoursUsed', 'Centrifuge_NumberOfHoursUsed', 'EquipmentUsageTracker', 'OtherEquipment.CentrifugeNumberOfHoursUsed', 'float', 'false', 'true', 'sensorDataSet_9', 'OtherEquipment')

/* Tags for Coupler */
	insert into dbo.FieldPoints values('CouplerConnectionStatus', 'CouplerConnectionStatus', 'FieldPoint', 'Coupler.couplerConnectionStatus', 'bool', 'false', 'true', 'sensorDataSet_10', 'EK1100_Coupler')