insert into dbo.SensorsDataSet values('sensorDataSet_1', 'SensorDataSet_1', null, 'Reactor_1')
insert into dbo.SensorsDataSet values('sensorDataSet_2', 'SensorDataSet_2', null, 'Reactor_2')
insert into dbo.SensorsDataSet values('sensorDataSet_3', 'SensorDataSet_3', null, 'Reactor_3')
insert into dbo.SensorsDataSet values('sensorDataSet_4', 'SensorDataSet_4', null, 'Reactor_4')
insert into dbo.SensorsDataSet values('sensorDataSet_5', 'SensorDataSet_5', null, 'Reactor_5')
insert into dbo.SensorsDataSet values('sensorDataSet_6', 'SensorDataSet_6', null, 'Reactor_6')
insert into dbo.SensorsDataSet values('sensorDataSet_7', 'SensorDataSet_7', null, '6TR_Chiller')
insert into dbo.SensorsDataSet values('sensorDataSet_8', 'SensorDataSet_8', null, '10TR_Chiller')
insert into dbo.SensorsDataSet values('sensorDataSet_9', 'SensorDataSet_9', null, 'OtherEquipment')
insert into dbo.SensorsDataSet values('sensorDataSet_10', 'SensorDataSet_10', null, 'EK1100_Coupler')
/*
insert into dbo.SensorsDataSet values('reactorSensors_1', 'Reactor Sensors', 'Reactor', 'Reactor_1')
insert into dbo.SensorsDataSet values('hcSensors_1', 'HC Sensors', 'HC', 'Reactor_1')
insert into dbo.SensorsDataSet values('stirrerSensors_1', 'Stirrer Sensors', 'Stirrer', 'Reactor_1')
insert into dbo.SensorsDataSet values('batchSensors_1', 'Batch Sensors', null, 'Reactor_1')

insert into dbo.SensorsDataSet values('reactorSensors_2', 'Reactor Sensors', 'Reactor', 'Reactor_2')
insert into dbo.SensorsDataSet values('hcSensors_2', 'HC Sensors', 'HC', 'Reactor_2')
insert into dbo.SensorsDataSet values('stirrerSensors_2', 'Stirrer Sensors', 'Stirrer', 'Reactor_2')
insert into dbo.SensorsDataSet values('batchSensors_2', 'Batch Sensors', null, 'Reactor_2')

insert into dbo.SensorsDataSet values('reactorSensors_3', 'Reactor Sensors', 'Reactor', 'Reactor_3')
insert into dbo.SensorsDataSet values('hcSensors_3', 'HC Sensors', 'HC', 'Reactor_3')
insert into dbo.SensorsDataSet values('stirrerSensors_3', 'Stirrer Sensors', 'Stirrer', 'Reactor_3')
insert into dbo.SensorsDataSet values('batchSensors_3', 'Batch Sensors', null, 'Reactor_3')

insert into dbo.SensorsDataSet values('reactorSensors_4', 'Reactor Sensors', 'Reactor', 'Reactor_4')
insert into dbo.SensorsDataSet values('hcSensors_4', 'HC Sensors', 'HC', 'Reactor_4')
insert into dbo.SensorsDataSet values('stirrerSensors_4', 'Stirrer Sensors', 'Stirrer', 'Reactor_4')
insert into dbo.SensorsDataSet values('batchSensors_4', 'Batch Sensors', null, 'Reactor_4')

insert into dbo.SensorsDataSet values('reactorSensors_5', 'Reactor Sensors', 'Reactor', 'Reactor_5')
insert into dbo.SensorsDataSet values('hcSensors_5', 'HC Sensors', 'HC', 'Reactor_5')
insert into dbo.SensorsDataSet values('stirrerSensors_5', 'Stirrer Sensors', 'Stirrer', 'Reactor_5')
insert into dbo.SensorsDataSet values('batchSensors_5', 'Batch Sensors', null, 'Reactor_5')

insert into dbo.SensorsDataSet values('reactorSensors_6', 'Reactor Sensors', 'Reactor', 'Reactor_6')
insert into dbo.SensorsDataSet values('hcSensors_6', 'HC Sensors', 'HC', 'Reactor_6')
insert into dbo.SensorsDataSet values('stirrerSensors_6', 'Stirrer Sensors', 'Stirrer', 'Reactor_6')
insert into dbo.SensorsDataSet values('batchSensors_6', 'Batch Sensors', null, 'Reactor_6')

insert into dbo.SensorsDataSet values('traneChillerSensors_1', 'Trane Chiller Sensors 1', 'TraneChiller', '6TR_Chiller')
insert into dbo.SensorsDataSet values('6TRSensors_1', '6TR Sensors', '6TR', '6TR_Chiller')

insert into dbo.SensorsDataSet values('traneChillerSensors_2', 'Trane Chiller Sensors 2', 'TraneChiller', '10TR_Chiller')
insert into dbo.SensorsDataSet values('10TRSensors_1', '10TR Sensors', '10TR', '10TR_Chiller')

insert into dbo.SensorsDataSet values('otherSensors', 'Other Sensors', 'Other', 'OtherEquipment')
insert into dbo.SensorsDataSet values('centirfugeSensors', 'Centrifuge Sensors', 'Centrifuge', 'OtherEquipment')
insert into dbo.SensorsDataSet values('scrubberSensors_1', 'Scrubber Sensors 1', 'Scrubber_1', 'OtherEquipment')
insert into dbo.SensorsDataSet values('scrubberSensors_2', 'Scrubber Sensors 2', 'Scrubber_2', 'OtherEquipment')
insert into dbo.SensorsDataSet values('scrubberSensors_3', 'Scrubber Sensors 3', 'Scrubber_3', 'OtherEquipment')
insert into dbo.SensorsDataSet values('ahuSensors', 'Ahu Sensors', 'Ahu', 'OtherEquipment')
insert into dbo.SensorsDataSet values('couplerSensors', 'Coupler Sensors', 'Coupler', 'EK1100_Coupler')
*/