/* Tags for Field Points of Equipments connected to Reactor */
delete from dbo.CommandPoints
delete from dbo.FieldPoints

/*insert into dbo.FieldPoints values('', '', '', '', '', '', '', '', '')*/

/* Tags for Reactor 1 */
	insert into dbo.FieldPoints values('UsedNow', 'Reactor_1|UsedNow', 'FieldPoint', 'R1.UsedNow', 'bool', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('EmergencyStatus', 'EmergencyStatus', 'FieldPoint', 'R1.EmergencyStatus', 'bool', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('BatchName', 'BatchName', 'FieldPoint', 'R1.BatchText_1', 'string', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('BatchNumber', 'BatchNumber', 'FieldPoint', 'R1.BatchText_2', 'string', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('BatchRemarks', 'BatchRemarks', 'FieldPoint', 'R1.BatchText_3', 'string', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('BatchStatus', 'BatchStatus', 'FieldPoint', 'R1.BatchText_4', 'string', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('BatchScientistName', 'BatchScientistName', 'FieldPoint', 'R1.BatchText_5', 'string', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	/*insert into dbo.FieldPoints values('Valve_1', 'Valve_1', 'FieldPoint', 'IO.R1.VentValve.Output', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_2', 'Valve_2', 'FieldPoint', 'IO.R1.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_4', 'Valve_4', 'FieldPoint', 'IO.R2.VentValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.R2.N2PurgeValve', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	*/

	
	insert into dbo.FieldPoints values('Valve_1', 'Valve_1', 'FieldPoint', 'IO.Vessels[0].Valves[0].bStart', 'bool', 'true', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_2', 'Valve_2', 'FieldPoint', 'IO.Vessels[0].Valves[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_3', 'Valve_3', 'FieldPoint', 'IO.Vessels[0].Valves[2].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_4', 'Valve_4', 'FieldPoint', 'IO.Vessels[1].Valves[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_5', 'Valve_5', 'FieldPoint', 'IO.Vessels[1].Valves[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_6', 'Valve_6', 'FieldPoint', 'IO.Vessels[1].Valves[3].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_7', 'Valve_7', 'FieldPoint', 'IO.Vessels[1].Valves[2].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_8', 'Valve_8', 'FieldPoint', 'IO.Vessels[2].Valves[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_9', 'Valve_9', 'FieldPoint', 'IO.Vessels[2].Valves[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_10', 'Valve_10', 'FieldPoint', 'IO.Vessels[2].Valves[4].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_11', 'Valve_11', 'FieldPoint', 'IO.Vessels[2].Valves[2].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_12', 'Valve_12', 'FieldPoint', 'IO.Vessels[3].Valves[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_13', 'Valve_13', 'FieldPoint', 'IO.Vessels[3].Valves[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_14', 'Valve_14', 'FieldPoint', 'IO.Vessels[3].Valves[4].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_15', 'Valve_15', 'FieldPoint', 'IO.Vessels[3].Valves[2].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_16', 'Valve_16', 'FieldPoint', 'IO.Vessels[5].Valves[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_17', 'Valve_17', 'FieldPoint', 'IO.Vessels[5].Valves[3].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_18', 'Valve_18', 'FieldPoint', 'IO.Vessels[5].Valves[4].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_19', 'Valve_19', 'FieldPoint', 'IO.Vessels[5].Valves[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_20', 'Valve_20', 'FieldPoint', 'IO.Vessels[5].Valves[2].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_21', 'Valve_21', 'FieldPoint', 'IO.Vessels[6].Valves[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_22', 'Valve_22', 'FieldPoint', 'IO.Vessels[6].Valves[4].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_23', 'Valve_23', 'FieldPoint', 'IO.Vessels[6].Valves[3].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_24', 'Valve_24', 'FieldPoint', 'IO.Vessels[6].Valves[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_25', 'Valve_25', 'FieldPoint', 'IO.Vessels[6].Valves[2].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_26', 'Valve_26', 'FieldPoint', 'IO.Reactors[1].Valves[4].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_27', 'Valve_27', 'FieldPoint', 'IO.Reactors[1].Valves[6].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_28', 'Valve_28', 'FieldPoint', 'IO.Reactors[1].Valves[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_29', 'Valve_29', 'FieldPoint', 'IO.Reactors[1].Valves[2].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	--insert into dbo.FieldPoints values('Valve_30', 'Valve_30', 'FieldPoint', 'IO.CommonDrainValve.Output', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	--insert into dbo.FieldPoints values('Valve_31', 'Valve_31', 'FieldPoint', 'IO.Reactors[1].Valves[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_32', 'Valve_32', 'FieldPoint', 'IO.Vessels[7].Valves[3].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_33', 'Valve_33', 'FieldPoint', 'IO.Vessels[7].Valves[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_34', 'Valve_34', 'FieldPoint', 'IO.Vessels[7].Valves[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	--insert into dbo.FieldPoints values('Valve_35', 'Valve_35', 'FieldPoint', 'IO.DCM.TransferValve_1.Output', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	--insert into dbo.FieldPoints values('Valve_36', 'Valve_36', 'FieldPoint', 'IO.DCM.TransferValve_2.Output', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_37', 'Valve_37', 'FieldPoint', 'IO.Reactors[0].Valves[6].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_38', 'Valve_38', 'FieldPoint', 'IO.Reactors[0].Valves[4].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_39', 'Valve_39', 'FieldPoint', 'IO.Reactors[0].Valves[2].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	--insert into dbo.FieldPoints values('Valve_40', 'Valve_40', 'FieldPoint', 'IO.SS.TransferValve_1.Output', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	--insert into dbo.FieldPoints values('Valve_41', 'Valve_41', 'FieldPoint', 'IO.SS.TransferValve_2.Output', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_42', 'Valve_42', 'FieldPoint', 'IO.Reactors[0].Valves[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_43', 'Valve_43', 'FieldPoint', 'IO.Vessels[8].Valves[2].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_44', 'Valve_44', 'FieldPoint', 'IO.Vessels[8].Valves[4].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_45', 'Valve_45', 'FieldPoint', 'IO.Vessels[8].Valves[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_46', 'Valve_46', 'FieldPoint', 'IO.Vessels[8].Valves[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_47', 'Valve_47', 'FieldPoint', 'IO.Vessels[4].Valves[2].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_48', 'Valve_48', 'FieldPoint', 'IO.Vessels[4].Valves[4].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_49', 'Valve_49', 'FieldPoint', 'IO.Vessels[4].Valves[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_50', 'Valve_50', 'FieldPoint', 'IO.Vessels[4].Valves[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_51', 'Valve_51', 'FieldPoint', 'IO.Reactors[1].Valves[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_52', 'Valve_52', 'FieldPoint', 'IO.Reactors[0].Valves[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_53', 'Valve_53', 'FieldPoint', 'IO.Vessels[0].Valves[3].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Valve_54', 'Valve_54', 'FieldPoint', 'IO.Vessels[2].Valves[3].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')

	insert into dbo.FieldPoints values('Pump_1', 'Pump_1', 'FieldPoint', 'IO.Vessels[0].Pumps[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Pump_2', 'Pump_2', 'FieldPoint', 'IO.Vessels[1].Pumps[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Pump_3', 'Pump_3', 'FieldPoint', 'IO.Vessels[2].Pumps[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Pump_4', 'Pump_4', 'FieldPoint', 'IO.Vessels[3].Pumps[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Pump_5', 'Pump_5', 'FieldPoint', 'IO.Reactors[1].Pumps[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Pump_6', 'Pump_6', 'FieldPoint', 'IO.Vessels[7].Pumps[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	--insert into dbo.FieldPoints values('Pump_7', 'Pump_7', 'FieldPoint', 'IO.SS.TransferPump.Output', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Pump_8', 'Pump_8', 'FieldPoint', 'IO.Vessels[8].Pumps[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Pump_9', 'Pump_9', 'FieldPoint', 'IO.Vessels[4].Pumps[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Pump_10', 'Pump_10', 'FieldPoint', 'IO.Vessels[0].Pumps[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Pump_11', 'Pump_11', 'FieldPoint', 'IO.Vessels[2].Pumps[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Pump_12', 'Pump_12', 'FieldPoint', 'IO.Vessels[3].Pumps[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Pump_13', 'Pump_13', 'FieldPoint', 'IO.Vessels[5].Pumps[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Pump_14', 'Pump_14', 'FieldPoint', 'IO.Vessels[6].Pumps[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Pump_15', 'Pump_15', 'FieldPoint', 'IO.Vessels[8].Pumps[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Pump_16', 'Pump_16', 'FieldPoint', 'IO.Vessels[1].Pumps[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Pump_17', 'Pump_17', 'FieldPoint', 'IO.Vessels[7].Pumps[0].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	--insert into dbo.FieldPoints values('Pump_18', 'Pump_18', 'FieldPoint', 'IO.Vessels[8].Pumps[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')
	--insert into dbo.FieldPoints values('Pump_19', 'Pump_19', 'FieldPoint', 'IO.Vessels[4].Pumps[1].bStart', 'bool', 'false', 'false', 'sensorDataSet_1', 'Reactor_1')



	*/

	insert into dbo.CommandPoints select Label, SensorDataSetIdentifier, FieldDeviceIdentifier from dbo.FieldPoints where CHARINDEX('Valve_', Label) > 0 
	insert into dbo.CommandPoints select Label, SensorDataSetIdentifier, FieldDeviceIdentifier from dbo.FieldPoints where CHARINDEX('Pump_', Label) > 0 

	/*
	insert into dbo.FieldPoints values('Tls', 'Top Level Sensor', 'FieldPoint', 'R1.Tls', 'bool', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('Bls', 'Bottom Level Sensor', 'FieldPoint', 'R1.Bls', 'bool', 'false', 'true', 'sensorDataSet_1', 'Reactor_1')
	insert into dbo.FieldPoints values('', '', '', '', '', '', '', '', '')
	insert into dbo.FieldPoints values('', '', '', '', '', '', '', '', '')
	insert into dbo.FieldPoints values('', '', '', '', '', '', '', '', '')
	insert into dbo.FieldPoints values('', '', '', '', '', '', '', '', '')
	insert into dbo.FieldPoints values('', '', '', '', '', '', '', '', '')
	
	insert into dbo.FieldPoints values('', '', '', '', '', '', '', '', '')
	*/
