<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="ParameterParsingValue" Id="{47ec56ba-c46e-4aa9-a436-d2f0b27ae62e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION ParameterParsingValue : REAL
VAR_INPUT
	InputParameter:REAL;
END_VAR	
VAR
	ParsedStringValue:STRING;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Rounding up the given parameter 
ParsedStringValue:=Lreal_to_fmtstr(InputParameter,1,TRUE);

//Converting  String to real

ParameterParsingValue:=STRING_TO_REAL(ParsedStringValue);

]]></ST>
    </Implementation>
    <LineIds Name="ParameterParsingValue">
      <LineId Id="11" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="17" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>